# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-idbbxt6J5t4duMs5ZF9xv7o0c5nk5lk
"""

import numpy as np

a=[1,45,78,90]
type(a)

b=np.array(a)
b

type(b)

a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

print("total shape=",b.shape)
print("total element=", b.size)
print("total dimesion=",b.ndim)

a=np.zeros(4)
a

a=np.zeros((2,3))
a

a=np.ones(3)
a

a=np.ones((3,4))
a

a=np.eye(3)
a

a=np.eye(3,4)
a

a=np.diag([1,45,78,90])
a

a=np.random.randint(1,10,3)
a

a=np.random.rand(5)
a

a=np.random.rand(5,2)
a

np.random.seed(6666)
a=np.random.randint(1,10,3)
a

a=np.random.randint(1,50,12)
a

a.reshape(2,6)

a.reshape(6,2)

a.reshape(3,4)

a.reshape(4,3)

a=np.array([10,20,30,40,50])
b=a[2:4].copy()
b[:]=0
b

a

a =np.arange(1,5)
a= a.reshape(2,2)

b=np.arange(5,9)
b

b=b.reshape(2,2)
b

a+b

a-b

a.dot(b)

a=np.linspace(1,2,5)
a

a=np.arange(1,16)
a

a>10

b=a>10
a[b]

a[a%2==0]

a[a%2 !=0]

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,10,11,12])

np.hstack((a,b,c))

np.vstack((a,b,c))

#pandas

a={'brand':'kia','model':'celtos','year':2024}
a

type(a)

for i in a.keys():
  print(i)

for i in a.values():
  print(i)

for x,y in a.items():
  print(x,y)

a

a.pop('brand')

a

a.popitem()

a

a.clear()

a

import pandas as pd

a={
    "emp_id":[1,2,3,4,5],
    "emp_name":['sam','raj','ankit','rahul','pallvi'],
    "working hours":[8,9,8,8,7],
    "salary":[23000,25000,21000,30000,36000]
}

df=pd.DataFrame(a)
df

array=np.array([1,2,3,4,5,6])
print(array)

random_integers=np.random.randint(1,101,size=10)
print(random_integers)

array=np.arange(10,21)
print(array)

array=[5 for _ in range(10)]
array=[5]*10
print(array)

import numpy as np
array_2d=np.random(1,11,size=(3,3))
print("generated 3*3 array:")

